name: Capture IP

on:
  push:
    branches:
      - main

jobs:
  capture-ip:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Run capture.bat
        run: .\capture.bat
