name: Capture IP

on:
  push:
    branches:
      - main

jobs:
  capture-ip:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Capture IP
        run: |
          ipconfig | find "IPv4 Address" > captured_ip.txt
          Get-Content captured_ip.txt | ForEach-Object { $_ -replace '.*:\s*(.*)', '$1' } | Set-Content captured_ip_cleaned.txt
          echo "::set-output name=user_ip::$(Get-Content captured_ip_cleaned.txt)"

      - name: Upload IP
        uses: actions/upload-artifact@v2
        with:
          name: captured-ip
          path: ${{ runner.workspace }}/captured_ip_cleaned.txt
