name: Capture IP

on:
  push:
    branches:
      - main

jobs:
  capture-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Display captured IP addresses
        run: |
          cat captured_ip.txt

      - name: Upload IP
        uses: actions/upload-artifact@v2
        with:
          name: captured-ip
          path: captured_ip.txt
