name: Capture IP

on:
  push:
    branches:
      - main

jobs:
  capture-ip:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Capture IP
        run: |
          mkdir -p .github/workflows/captured-ip
          ipconfig | find "IPv4 Address" > .github/workflows/captured-ip/captured_ip.txt

      - name: Upload IP
        uses: actions/upload-artifact@v2
        with:
          name: captured-ip
          path: .github/workflows/captured-ip/captured_ip.txt
